/* generated by scripts/build-writing.mjs — do not edit by hand */
#ifndef WRITING_MANIFEST_H
#define WRITING_MANIFEST_H

typedef struct
{
    const char* slug;
    const char* view;
    const char* title;
    const char* desc;
} WritingPost;

static const WritingPost kWritingPosts[] = {
    {"building-c-copper", "writing/building-c-copper.html", "Building c-copper: what a web framework in C teaches you", "Why I wrote the framework serving this page in C99 with zero dependencies, the decisions that mattered, and what the numbers say."},
};

#endif /* WRITING_MANIFEST_H */
