/* generated by scripts/build-writing.mjs — do not edit by hand */
#ifndef WRITING_MANIFEST_H
#define WRITING_MANIFEST_H

typedef struct
{
    const char* slug;
    const char* view;
    const char* title;
    const char* desc;
} WritingPost;

static const WritingPost kWritingPosts[] = {
    {"on-being-pragmatic", "writing/on-being-pragmatic.html", "On being pragmatic", "Correct and right are different things. Correct means the program does what it needs to do for the people who need it, at a cost they can afford. Right means it matches an idea the author had. Most of the damage in this industry lives in the gap."},
    {"building-c-copper", "writing/building-c-copper.html", "Building c-copper: what a web framework in C teaches you", "Why I wrote the framework serving this page in C99 with zero dependencies, the decisions that mattered, and what the numbers say."},
};

#endif /* WRITING_MANIFEST_H */
