// Build-time markdown pipeline: writing/*.md -> views/writing/*.html
// + views/writing/index.html + controllers/writing_manifest.h
// Zero runtime deps preserved: the C server only ever serves generated HTML.
import { marked } from "marked";
import { readFileSync, writeFileSync, readdirSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const SRC = join(root, "writing");
const OUT = join(root, "views", "writing");
mkdirSync(OUT, { recursive: true });

function parseFrontmatter(raw) {
  const m = raw.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!m) throw new Error("missing frontmatter block");
  const meta = {};
  for (const line of m[1].split("\n")) {
    const i = line.indexOf(":");
    if (i > 0) meta[line.slice(0, i).trim()] = line.slice(i + 1).trim();
  }
  return { meta, body: m[2] };
}

// The C template engine interprets {{...}} and @csrf — generated HTML must
// never contain either, or article content would be mangled at render time.
const neutralize = (html) =>
  html.replace(/\{\{/g, "&#123;&#123;").replace(/\}\}/g, "&#125;&#125;").replace(/@csrf/g, "&#64;csrf");

const posts = [];
for (const f of readdirSync(SRC).filter((f) => f.endsWith(".md")).sort()) {
  const { meta, body } = parseFrontmatter(readFileSync(join(SRC, f), "utf8"));
  for (const k of ["slug", "title", "description", "date"])
    if (!meta[k]) throw new Error(`${f}: frontmatter missing "${k}"`);
  if (!/^[a-z0-9-]+$/.test(meta.slug)) throw new Error(`${f}: slug must be [a-z0-9-]`);
  const html = neutralize(marked.parse(body));

  writeFileSync(
    join(OUT, `${meta.slug}.html`),
    `<!-- generated from writing/${f} — do not edit by hand -->
<div class="text-[11px] font-mono text-slate-500">
  <a href="/writing" class="text-emerald-400 hover:text-emerald-300 transition-colors">&larr; ~/writing</a>
  <span class="mx-2">/</span><span>${meta.slug}</span>
</div>

<article class="bg-[#121214] border border-slate-800 rounded-lg p-6 lg:p-10">
  <div class="mb-8 pb-6 border-b border-slate-800">
    <span class="text-xs font-mono uppercase tracking-wider text-emerald-400 font-bold block mb-2">Writing // ${meta.date}</span>
    <h1 class="text-2xl sm:text-3xl font-bold text-slate-100 tracking-tight leading-tight">${meta.title}</h1>
  </div>
  <div class="prose-article max-w-3xl">
${html}
  </div>
</article>

<div class="text-[11px] font-mono">
  <a href="/writing" class="text-slate-500 hover:text-emerald-400 transition-colors">back to ~/writing</a>
</div>
`,
  );
  posts.push(meta);
}

posts.sort((a, b) => (a.date < b.date ? 1 : -1));

// index view
writeFileSync(
  join(OUT, "index.html"),
  `<!-- generated by scripts/build-writing.mjs — do not edit by hand -->
<div class="bg-[#121214] border border-slate-800 rounded-lg p-6 lg:p-8">
  <span class="text-xs font-mono uppercase tracking-wider text-emerald-400 font-bold block mb-2">$ cat ~/writing/*.md</span>
  <h2 class="text-2xl sm:text-3xl font-bold text-slate-100 tracking-tight leading-tight mb-3">Build logs, written up.</h2>
  <p class="text-xs sm:text-sm text-slate-400 leading-relaxed max-w-2xl">
    Long-form writeups of things built here — canonical on this domain, cross-posted elsewhere.
    Markdown in the repo, compiled to HTML at build time, served by the C framework like everything else.
  </p>
</div>

<section class="bg-[#121214] border border-slate-800 rounded-lg overflow-hidden">
  <header class="flex items-center justify-between px-5 py-3 bg-[#0E0E10] border-b border-slate-800">
    <span class="text-[10px] font-mono uppercase tracking-widest text-emerald-400 font-bold">// POSTS</span>
    <span class="text-[9px] font-mono text-slate-500">${posts.length} ${posts.length === 1 ? "entry" : "entries"}</span>
  </header>
  <ul class="dim-list divide-y divide-slate-800/70">
${posts
  .map(
    (p) => `    <li>
      <a href="/writing/${p.slug}" class="block px-5 py-4 hover:bg-emerald-500/5 transition-colors group">
        <div class="flex items-center justify-between gap-3 mb-1">
          <span class="text-sm font-semibold text-slate-100 group-hover:text-emerald-400 transition-colors">${p.title}</span>
          <span class="text-[10px] font-mono text-slate-500 shrink-0">${p.date}</span>
        </div>
        <p class="text-[11px] text-slate-400 leading-relaxed">${p.description}</p>
      </a>
    </li>`,
  )
  .join("\n")}
  </ul>
</section>
`,
);

// C manifest — compile-time allowlist for the controller
writeFileSync(
  join(root, "controllers", "writing_manifest.h"),
  `/* generated by scripts/build-writing.mjs — do not edit by hand */
#ifndef WRITING_MANIFEST_H
#define WRITING_MANIFEST_H

typedef struct
{
    const char* slug;
    const char* view;
    const char* title;
    const char* desc;
} WritingPost;

static const WritingPost kWritingPosts[] = {
${posts
  .map(
    (p) =>
      `    {"${p.slug}", "writing/${p.slug}.html", "${p.title.replace(/"/g, '\\"')}", "${p.description.replace(/"/g, '\\"')}"},`,
  )
  .join("\n")}
};

#endif /* WRITING_MANIFEST_H */
`,
);

console.log(`writing: ${posts.length} post(s) -> views/writing/ + controllers/writing_manifest.h`);
